CREATE DATABASE empresa;
USE empresa;

CREATE TABLE productos(
IDMATERIAL	VARCHAR(20) NOT NULL PRIMARY KEY,
NOMBREMATERIAL varchar(50),
DESCRIPCION	VARCHAR(60),
UNIDADMEDIDA	VARCHAR(10),
PRECIO1	DOUBLE(13,3)
)ENGINE=INNODB;

CREATE TABLE clientes(
IDCLIENTE	INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
RAZON_SOCIAL	VARCHAR(60),
RFC		VARCHAR(15)
)ENGINE=INNODB;

CREATE TABLE documento(
IDCODIGO	INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
IDCLIENTE	INT(11),
RAZON_SOCIAL	VARCHAR(60),
RFC		VARCHAR(15),
SUBTOTAL	DOUBLE(13,3),
IVA		DOUBLE(13,3),
TOTAL		DOUBLE(13,3),
FOREIGN KEY (IDCLIENTE) REFERENCES clientes(IDCLIENTE)
)ENGINE=INNODB;

CREATE TABLE documentorenglon(
IDCODIGO	INT(11),
IDMATERIAL	VARCHAR(20),
UNIDAD_MEDIDA	VARCHAR(10),
CANTIDAD	DOUBLE(13,3),
PRECIO1	DOUBLE(13,3),
 FOREIGN KEY (IDMATERIAL) REFERENCES productos(IDMATERIAL),
 FOREIGN KEY (IDCODIGO) REFERENCES documento(IDCODIGO)
)ENGINE=INNODB;

/*Datos para materiales*/
INSERT INTO productos(IDMATERIAL,NOMBREMATERIAl,DESCRIPCION,UNIDADMEDIDA,PRECIO1)VALUES (UUID_SHORT(),'Pintura','Lorem Ipsum is simply dummy text of the printing','litros',488);
INSERT INTO productos(IDMATERIAL,NOMBREMATERIAl,DESCRIPCION,UNIDADMEDIDA,PRECIO1)VALUES (UUID_SHORT(),'Aislante termico','Lorem Ipsum is simply dummy text of the printing','litros',2900);
INSERT INTO productos(IDMATERIAL,NOMBREMATERIAl,DESCRIPCION,UNIDADMEDIDA,PRECIO1)VALUES (UUID_SHORT(),'Sellador impercool','Lorem Ipsum is simply dummy text of the printing','litros',253.88);
INSERT INTO productos(IDMATERIAL,NOMBREMATERIAl,DESCRIPCION,UNIDADMEDIDA,PRECIO1)VALUES (UUID_SHORT(),'Imperm fibrato','Lorem Ipsum is simply dummy text of the printing','litros',1395.16);
INSERT INTO productos(IDMATERIAL,NOMBREMATERIAl,DESCRIPCION,UNIDADMEDIDA,PRECIO1)VALUES (UUID_SHORT(),'cemento cemex','cemento marca cemex','kilos',129.92);
INSERT INTO productos(IDMATERIAL,NOMBREMATERIAl,DESCRIPCION,UNIDADMEDIDA,PRECIO1)VALUES (UUID_SHORT(),'niplicimbra tubo','niplicimbra tubo de 15cm x 3mt largo','Metros',129.92);
INSERT INTO productos(IDMATERIAL,NOMBREMATERIAl,DESCRIPCION,UNIDADMEDIDA,PRECIO1)VALUES (UUID_SHORT(),'alambre de acero','100 metros de alamabre de acero','Metros',100);
INSERT INTO productos(IDMATERIAL,NOMBREMATERIAl,DESCRIPCION,UNIDADMEDIDA,PRECIO1)VALUES (UUID_SHORT(),'pegamento pvc','pegamento para pvc marca tangit de 225 gramos','Gramos',120);
INSERT INTO productos(IDMATERIAL,NOMBREMATERIAl,DESCRIPCION,UNIDADMEDIDA,PRECIO1)VALUES (UUID_SHORT(),'Tanque Dolbo','Tanque Dolbo eros blanco una pieza','pieza',600);
INSERT INTO productos(IDMATERIAL,NOMBREMATERIAl,DESCRIPCION,UNIDADMEDIDA,PRECIO1)VALUES (UUID_SHORT(),'Espejo rectangular','Espejo rectangular de 60X45 bellisi','pieza',170);
/*datos para clientes*/

INSERT INTO clientes(RAZON_SOCIAL,RFC)VALUES ('Minas materiales','OFHKSDFHDL');
INSERT INTO clientes(RAZON_SOCIAL,RFC)VALUES ('la casa del castor','PREEHDHEFD2');
INSERT INTO clientes(RAZON_SOCIAL,RFC)VALUES ('Todo materiales','GDSKSAJDSA');
INSERT INTO clientes(RAZON_SOCIAL,RFC)VALUES ('Materiales castillo','TQWPACKXOP');
INSERT INTO clientes(RAZON_SOCIAL,RFC)VALUES ('Plomeria martinez','PQH65OK1LQ');
INSERT INTO clientes(RAZON_SOCIAL,RFC)VALUES ('El plomero','N12HDKPA0T');
INSERT INTO clientes(RAZON_SOCIAL,RFC)VALUES ('Carpinteria lopez','LQW09HAKKW');
INSERT INTO clientes(RAZON_SOCIAL,RFC)VALUES ('Materiales el azulejo','LPWEYSH09H');
INSERT INTO clientes(RAZON_SOCIAL,RFC)VALUES ('Carpinteria Lucas','PQWJDHS09A');
INSERT INTO clientes(RAZON_SOCIAL,RFC)VALUES ('Materiales los tres hermanos','LQGAQ120GDA');


